sudo: required
services:
  - docker

before_install:
  - docker build -t alejandro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alejandro/docker-react npm run test

language: generic